use crate::TransactionId;

pub const SOPHIA_IPC_MAGIC: u32 = 0x4850_4f53;
pub const SOPHIA_IPC_VERSION: u16 = 1;
pub const SOPHIA_IPC_HEADER_LEN: usize = 24;
pub const SOPHIA_IPC_MAX_PAYLOAD_LEN: usize = 64 * 1024;
pub const SOPHIA_IPC_MAX_ITEMS: usize = 1024;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IpcMessageKind {
    BrokerHealth = 3,
    XAuthorityRequest = 4,
    XAuthorityResponse = 5,
    PortalBrokerRequest = 6,
    PortalBrokerResponse = 7,
    PortalClipboardPayload = 8,
    WmV1ClientHello = 32,
    WmV1ServerWelcome = 33,
    WmV1SnapshotBegin = 34,
    WmV1SnapshotChunk = 35,
    WmV1SnapshotEnd = 36,
    WmV1ProjectionRequest = 37,
    WmV1ProjectionBegin = 38,
    WmV1ProjectionChunk = 39,
    WmV1ProjectionEnd = 40,
    WmV1ProjectionOutcome = 41,
    WmV1PolicyConfiguration = 42,
    WmV1PolicyConfigurationOutcome = 43,
    WmV1PolicyDirty = 44,
    WmV1SessionOperationRequest = 45,
    WmV1SessionOperationOutcome = 46,
    WmV1ProfilePrepare = 47,
    WmV1ProfilePrepared = 48,
    WmV1ProfileActivate = 49,
    WmV1ProfileActive = 50,
    WmV1ProfileRollback = 51,
    WmV1ProfileRolledBack = 52,
    OutputV1ClientHello = 64,
    OutputV1ServerWelcome = 65,
    OutputV1Snapshot = 66,
    OutputV1Proposal = 67,
    OutputV1Outcome = 68,
    BrokerV1ClientHello = 80,
    BrokerV1ServerWelcome = 81,
    BrokerV1Request = 82,
    BrokerV1Response = 83,
    ShellV1ClientHello = 96,
    ShellV1ServerWelcome = 97,
    ShellV1DescriptorSnapshot = 98,
    ShellV1Candidate = 99,
    ShellV1CandidateOutcome = 100,
    ShellV1Activation = 101,
    ShellV1ActivationAck = 102,
    ShellTabsBegin = 103,
    ShellTabsGroup = 104,
    ShellTabsEntry = 105,
    ShellTabsEnd = 106,
    ShellTabsCandidate = 107,
    ShellShortcutsBegin = 108,
    ShellShortcutsEntry = 109,
    ShellShortcutsEnd = 110,
    ShellReferenceRequest = 111,
    ShellReferenceCandidate = 112,
    ShellReferenceOutcome = 113,
    ShellApplicationsBegin = 114,
    ShellApplicationsEntry = 115,
    ShellApplicationsEnd = 116,
    ShellLauncherRequest = 117,
    ShellLauncherCandidate = 118,
    ShellLauncherOutcome = 119,
    ShellLauncherActivation = 120,
    ShellLauncherActivationAck = 121,
    ShellLaunchOutcome = 122,
    ShellContentAdmissionRefused = 160,
    ShellContentLimits = 161,
    ShellContentOutputFacts = 162,
    ShellContentAllocationRequest = 163,
    ShellContentAllocationResult = 164,
    ShellContentResourceBegin = 165,
    ShellContentResourceStatus = 166,
    ShellContentResourceChunk = 167,
    ShellContentResourceEnd = 168,
    ShellContentResourceCancel = 169,
    ShellContentResourceRetire = 170,
    ShellContentResourceReleased = 171,
    ShellContentCandidateBegin = 172,
    ShellContentCandidateChunk = 173,
    ShellContentCandidateEnd = 174,
    ShellContentCandidateOutcome = 175,
    ShellContentFrameDemand = 176,
    ShellContentFramePermit = 177,
    ShellContentFrameDemandCancel = 178,
    ShellContentAction = 179,
    ShellContentActionAck = 180,
    ShellIndicatorsBegin = 181,
    ShellIndicatorsOutputStatus = 182,
    ShellIndicatorsEntry = 183,
    ShellIndicatorsEnd = 184,
    ShellIndicatorActivate = 185,
    ShellIndicatorActivateOutcome = 186,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct IpcFrameHeader {
    pub message_kind: IpcMessageKind,
    pub transaction: TransactionId,
    pub payload_len: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum IpcCodecError {
    Truncated,
    BadMagic,
    UnsupportedVersion(u16),
    UnknownMessageKind(u16),
    PayloadTooLarge(usize),
    ReservedNonZero(u32),
    TrailingBytes(usize),
    CountTooLarge {
        count: usize,
        max: usize,
    },
    TextTooLarge {
        field: &'static str,
        len: usize,
        max: usize,
    },
    FieldTooLarge {
        field: &'static str,
        len: usize,
        max: usize,
    },
    InvalidTransaction(u64),
    InvalidProfileIdentity(&'static str),
    InvalidUtf8 {
        field: &'static str,
    },
    InvalidEnum {
        field: &'static str,
        value: u32,
    },
    InvalidBool {
        field: &'static str,
        value: u8,
    },
    InvalidRecord(&'static str),
}
