// @generated by sophia-policy-protocol-gen; do not edit.
// Source: protocol/sophia-wm-v1.kdl

use super::cursor::{Cursor, push_i32, push_u16, push_u32, push_u64};
use super::frame::{decode_frame, encode_frame};
use super::types::{IpcCodecError, IpcMessageKind};
use crate::TransactionId;

pub const SOPHIA_WM_INTERFACE_MAJOR: u16 = 1;
pub const SOPHIA_WM_INTERFACE_REVISION: u16 = 3;
pub const SOPHIA_WM_MAX_OUTPUTS: usize = 16;
pub const SOPHIA_WM_MAX_SURFACES: usize = 1024;
pub const SOPHIA_WM_MAX_BINDINGS: usize = 256;

pub const SOPHIA_WM_CAPABILITY_BINDINGS: u64 = 1 << 0;
pub const SOPHIA_WM_CAPABILITY_ACTIONS: u64 = 1 << 1;
pub const SOPHIA_WM_CAPABILITY_MULTI_OUTPUT: u64 = 1 << 2;
pub const SOPHIA_WM_CAPABILITY_POINTER_INTERACTIONS: u64 = 1 << 3;
pub const SOPHIA_WM_CAPABILITY_CHROME: u64 = 1 << 4;
pub const SOPHIA_WM_CAPABILITY_POLICY_DIRTY: u64 = 1 << 5;
pub const SOPHIA_WM_CAPABILITY_CONFIGURATION: u64 = 1 << 6;
pub const SOPHIA_WM_CAPABILITY_SESSION_OPERATIONS: u64 = 1 << 7;
pub const SOPHIA_WM_CAPABILITY_INDICATORS: u64 = 1 << 8;
pub const SOPHIA_WM_CAPABILITY_PROFILE_ACTIVATION: u64 = 1 << 9;
pub const SOPHIA_WM_CAPABILITY_LAUNCH_PLACEMENT: u64 = 1 << 10;
pub const SOPHIA_WM_CAPABILITY_TAB_GROUPS: u64 = 1 << 11;
pub const SOPHIA_WM_CAPABILITY_TRANSLATION_GROUPS: u64 = 1 << 12;
pub const SOPHIA_WM_CAPABILITY_POINTER_FOCUS: u64 = 1 << 13;

pub const SOPHIA_WM_OUTCOME_COMMITTED: u16 = 1;
pub const SOPHIA_WM_OUTCOME_REJECTED_STALE: u16 = 2;
pub const SOPHIA_WM_OUTCOME_REJECTED_INVALID: u16 = 3;
pub const SOPHIA_WM_OUTCOME_TIMED_OUT: u16 = 4;
pub const SOPHIA_WM_OUTCOME_DISCONNECTED: u16 = 5;
pub const SOPHIA_WM_OUTCOME_PROFILE_ACCEPTED: u16 = 1;
pub const SOPHIA_WM_OUTCOME_PROFILE_REJECTED_IDENTITY: u16 = 2;
pub const SOPHIA_WM_OUTCOME_PROFILE_REJECTED_STATE: u16 = 3;

pub const SNAPSHOT_OUTPUT_RECORD_KIND: u16 = 1;
pub const SNAPSHOT_OUTPUT_RECORD_SIZE: usize = 56;
pub const SNAPSHOT_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotOutputRecord {
    pub output: u64,
    pub generation: u64,
    pub focus_index: u32,
    pub focus_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub work_x: i32,
    pub work_y: i32,
    pub work_width: i32,
    pub work_height: i32,
}

pub fn encode_wm_v1_snapshot_output_records(
    records: &[WmV1SnapshotOutputRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 16 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 56);
    for record in records {
        push_u64(&mut data, record.output);
        push_u64(&mut data, record.generation);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.work_x);
        push_i32(&mut data, record.work_y);
        push_i32(&mut data, record.work_width);
        push_i32(&mut data, record.work_height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotOutputRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(IpcCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(56)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let generation = cursor.u64()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let work_x = cursor.i32()?;
        let work_y = cursor.i32()?;
        let work_width = cursor.i32()?;
        let work_height = cursor.i32()?;
        records.push(WmV1SnapshotOutputRecord {
            output,
            generation,
            focus_index,
            focus_generation,
            x,
            y,
            width,
            height,
            work_x,
            work_y,
            work_width,
            work_height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_SURFACE_RECORD_KIND: u16 = 2;
pub const SNAPSHOT_SURFACE_RECORD_SIZE: usize = 80;
pub const SNAPSHOT_SURFACE_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotSurfaceRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub current_output: u64,
    pub capability_bits: u16,
    pub kind: u16,
    pub request_state_bits: u16,
    pub current_state_bits: u16,
    pub transient_index: u32,
    pub transient_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub min_width: i32,
    pub min_height: i32,
    pub max_width: i32,
    pub max_height: i32,
    pub exact_width: i32,
    pub exact_height: i32,
}

pub fn encode_wm_v1_snapshot_surface_records(
    records: &[WmV1SnapshotSurfaceRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 1024 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 80);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_u64(&mut data, record.current_output);
        push_u16(&mut data, record.capability_bits);
        push_u16(&mut data, record.kind);
        push_u16(&mut data, record.request_state_bits);
        push_u16(&mut data, record.current_state_bits);
        push_u32(&mut data, record.transient_index);
        push_u32(&mut data, record.transient_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.min_width);
        push_i32(&mut data, record.min_height);
        push_i32(&mut data, record.max_width);
        push_i32(&mut data, record.max_height);
        push_i32(&mut data, record.exact_width);
        push_i32(&mut data, record.exact_height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_surface_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotSurfaceRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(IpcCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(80)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let current_output = cursor.u64()?;
        let capability_bits = cursor.u16()?;
        let kind = cursor.u16()?;
        let request_state_bits = cursor.u16()?;
        let current_state_bits = cursor.u16()?;
        let transient_index = cursor.u32()?;
        let transient_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let min_width = cursor.i32()?;
        let min_height = cursor.i32()?;
        let max_width = cursor.i32()?;
        let max_height = cursor.i32()?;
        let exact_width = cursor.i32()?;
        let exact_height = cursor.i32()?;
        records.push(WmV1SnapshotSurfaceRecord {
            surface_index,
            surface_generation,
            state_generation,
            current_output,
            capability_bits,
            kind,
            request_state_bits,
            current_state_bits,
            transient_index,
            transient_generation,
            x,
            y,
            width,
            height,
            min_width,
            min_height,
            max_width,
            max_height,
            exact_width,
            exact_height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_ACTION_RECORD_KIND: u16 = 3;
pub const SNAPSHOT_ACTION_RECORD_SIZE: usize = 140;
pub const SNAPSHOT_ACTION_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotActionRecord {
    pub action: u64,
    pub session_operation_slot: u16,
    pub name_len: u16,
    pub name: [u8; 128],
}

pub fn encode_wm_v1_snapshot_action_records(
    records: &[WmV1SnapshotActionRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 256 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 140);
    for record in records {
        push_u64(&mut data, record.action);
        push_u16(&mut data, record.session_operation_slot);
        push_u16(&mut data, record.name_len);
        data.extend_from_slice(&record.name);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_action_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotActionRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(IpcCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(140)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let action = cursor.u64()?;
        let session_operation_slot = cursor.u16()?;
        let name_len = cursor.u16()?;
        let mut name = [0u8; 128];
        name.copy_from_slice(cursor.slice(128)?);
        records.push(WmV1SnapshotActionRecord {
            action,
            session_operation_slot,
            name_len,
            name,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_SESSION_OPERATION_RECORD_KIND: u16 = 4;
pub const SNAPSHOT_SESSION_OPERATION_RECORD_SIZE: usize = 12;
pub const SNAPSHOT_SESSION_OPERATION_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotSessionOperationRecord {
    pub operation: u64,
    pub slot: u16,
    pub target_bits: u16,
}

pub fn encode_wm_v1_snapshot_session_operation_records(
    records: &[WmV1SnapshotSessionOperationRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 256 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 12);
    for record in records {
        push_u64(&mut data, record.operation);
        push_u16(&mut data, record.slot);
        push_u16(&mut data, record.target_bits);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_session_operation_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotSessionOperationRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(IpcCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(12)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let operation = cursor.u64()?;
        let slot = cursor.u16()?;
        let target_bits = cursor.u16()?;
        records.push(WmV1SnapshotSessionOperationRecord {
            operation,
            slot,
            target_bits,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_OUTPUT_RECORD_KIND: u16 = 1;
pub const PROJECTION_OUTPUT_RECORD_SIZE: usize = 24;
pub const PROJECTION_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutputRecord {
    pub output: u64,
    pub placement_count: u32,
    pub focus_index: u32,
    pub focus_generation: u32,
}

pub fn encode_wm_v1_projection_output_records(
    records: &[WmV1ProjectionOutputRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 16 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 24);
    for record in records {
        push_u64(&mut data, record.output);
        push_u32(&mut data, record.placement_count);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_u32(&mut data, 0);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionOutputRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(IpcCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(24)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let placement_count = cursor.u32()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let reserved = cursor.u32()?;
        if reserved != 0 {
            return Err(IpcCodecError::ReservedNonZero(reserved));
        }
        records.push(WmV1ProjectionOutputRecord {
            output,
            placement_count,
            focus_index,
            focus_generation,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_PLACEMENT_RECORD_KIND: u16 = 2;
pub const PROJECTION_PLACEMENT_RECORD_SIZE: usize = 60;
pub const PROJECTION_PLACEMENT_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionPlacementRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub requested_width: i32,
    pub requested_height: i32,
    pub crop_x: i32,
    pub crop_y: i32,
    pub crop_width: i32,
    pub crop_height: i32,
    pub transform: u16,
    pub presentation_bits: u16,
}

pub fn encode_wm_v1_projection_placement_records(
    records: &[WmV1ProjectionPlacementRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 1024 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 60);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.requested_width);
        push_i32(&mut data, record.requested_height);
        push_i32(&mut data, record.crop_x);
        push_i32(&mut data, record.crop_y);
        push_i32(&mut data, record.crop_width);
        push_i32(&mut data, record.crop_height);
        push_u16(&mut data, record.transform);
        push_u16(&mut data, record.presentation_bits);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_placement_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionPlacementRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(IpcCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(60)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let requested_width = cursor.i32()?;
        let requested_height = cursor.i32()?;
        let crop_x = cursor.i32()?;
        let crop_y = cursor.i32()?;
        let crop_width = cursor.i32()?;
        let crop_height = cursor.i32()?;
        let transform = cursor.u16()?;
        let presentation_bits = cursor.u16()?;
        records.push(WmV1ProjectionPlacementRecord {
            surface_index,
            surface_generation,
            state_generation,
            x,
            y,
            width,
            height,
            requested_width,
            requested_height,
            crop_x,
            crop_y,
            crop_width,
            crop_height,
            transform,
            presentation_bits,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_INDICATOR_RECORD_KIND: u16 = 3;
pub const PROJECTION_INDICATOR_RECORD_SIZE: usize = 64;
pub const PROJECTION_INDICATOR_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionIndicatorRecord {
    pub output: u64,
    pub slot: u32,
    pub indicator: u64,
    pub action: u64,
    pub state_bits: u16,
    pub label_len: u16,
    pub label: [u8; 32],
}

pub fn encode_wm_v1_projection_indicator_records(
    records: &[WmV1ProjectionIndicatorRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 256 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 64);
    for record in records {
        push_u64(&mut data, record.output);
        push_u32(&mut data, record.slot);
        push_u64(&mut data, record.indicator);
        push_u64(&mut data, record.action);
        push_u16(&mut data, record.state_bits);
        push_u16(&mut data, record.label_len);
        data.extend_from_slice(&record.label);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_indicator_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionIndicatorRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(IpcCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(64)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let slot = cursor.u32()?;
        let indicator = cursor.u64()?;
        let action = cursor.u64()?;
        let state_bits = cursor.u16()?;
        let label_len = cursor.u16()?;
        let mut label = [0u8; 32];
        label.copy_from_slice(cursor.slice(32)?);
        records.push(WmV1ProjectionIndicatorRecord {
            output,
            slot,
            indicator,
            action,
            state_bits,
            label_len,
            label,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_OUTPUT_STATUS_RECORD_KIND: u16 = 4;
pub const PROJECTION_OUTPUT_STATUS_RECORD_SIZE: usize = 48;
pub const PROJECTION_OUTPUT_STATUS_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutputStatusRecord {
    pub output: u64,
    pub focus_bits: u16,
    pub layout_len: u16,
    pub layout: [u8; 32],
}

pub fn encode_wm_v1_projection_output_status_records(
    records: &[WmV1ProjectionOutputStatusRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 16 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 48);
    for record in records {
        push_u64(&mut data, record.output);
        push_u16(&mut data, record.focus_bits);
        push_u16(&mut data, record.layout_len);
        push_u32(&mut data, 0);
        data.extend_from_slice(&record.layout);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_output_status_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionOutputStatusRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(IpcCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(48)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let focus_bits = cursor.u16()?;
        let layout_len = cursor.u16()?;
        let reserved = cursor.u32()?;
        if reserved != 0 {
            return Err(IpcCodecError::ReservedNonZero(reserved));
        }
        let mut layout = [0u8; 32];
        layout.copy_from_slice(cursor.slice(32)?);
        records.push(WmV1ProjectionOutputStatusRecord {
            output,
            focus_bits,
            layout_len,
            layout,
        });
    }
    cursor.finish()?;
    Ok(records)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ClientHello {
    pub minimum_revision: u16,
    pub maximum_revision: u16,
    pub capabilities: u64,
}

pub fn encode_wm_v1_client_hello_frame(
    message: &WmV1ClientHello,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.minimum_revision);
    push_u16(&mut payload, message.maximum_revision);
    push_u64(&mut payload, message.capabilities);
    encode_frame(
        IpcMessageKind::WmV1ClientHello,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_client_hello_frame(frame: &[u8]) -> Result<WmV1ClientHello, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ClientHello {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let minimum_revision = cursor.u16()?;
    let maximum_revision = cursor.u16()?;
    let capabilities = cursor.u64()?;
    cursor.finish()?;
    let message = WmV1ClientHello {
        minimum_revision,
        maximum_revision,
        capabilities,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ServerWelcome {
    pub selected_revision: u16,
    pub capabilities: u64,
    pub connection_epoch: u64,
    pub max_outputs: u16,
    pub max_bindings: u16,
    pub max_surfaces: u32,
    pub max_chunk_bytes: u32,
}

pub fn encode_wm_v1_server_welcome_frame(
    message: &WmV1ServerWelcome,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.selected_revision);
    push_u16(&mut payload, 0);
    push_u64(&mut payload, message.capabilities);
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.max_outputs);
    push_u16(&mut payload, message.max_bindings);
    push_u32(&mut payload, message.max_surfaces);
    push_u32(&mut payload, message.max_chunk_bytes);
    encode_frame(
        IpcMessageKind::WmV1ServerWelcome,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_server_welcome_frame(frame: &[u8]) -> Result<WmV1ServerWelcome, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ServerWelcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let selected_revision = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let capabilities = cursor.u64()?;
    let connection_epoch = cursor.u64()?;
    let max_outputs = cursor.u16()?;
    let max_bindings = cursor.u16()?;
    let max_surfaces = cursor.u32()?;
    let max_chunk_bytes = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1ServerWelcome {
        selected_revision,
        capabilities,
        connection_epoch,
        max_outputs,
        max_bindings,
        max_surfaces,
        max_chunk_bytes,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotBegin {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub active_output: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub surface_count: u32,
    pub action_count: u16,
    pub session_operation_count: u16,
}

pub fn encode_wm_v1_snapshot_begin_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.active_output);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.surface_count);
    push_u16(&mut payload, message.action_count);
    push_u16(&mut payload, message.session_operation_count);
    encode_frame(IpcMessageKind::WmV1SnapshotBegin, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let active_output = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let surface_count = cursor.u32()?;
    let action_count = cursor.u16()?;
    let session_operation_count = cursor.u16()?;
    cursor.finish()?;
    let message = WmV1SnapshotBegin {
        connection_epoch,
        scene_generation,
        active_output,
        chunk_count,
        output_count,
        surface_count,
        action_count,
        session_operation_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_snapshot_chunk_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1SnapshotChunk, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1SnapshotChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotEnd {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_snapshot_end_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1SnapshotEnd, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SnapshotEnd {
        connection_epoch,
        scene_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub policy_generation: u64,
    pub cause_kind: u16,
    pub interaction_phase: u16,
    pub interaction_kind: u16,
    pub interaction_axis: u16,
    pub activation_serial: u64,
    pub action: u64,
    pub target_index: u32,
    pub target_generation: u32,
    pub interaction_x: i32,
    pub interaction_y: i32,
    pub interaction_width: i32,
    pub interaction_height: i32,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_projection_request_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.policy_generation);
    push_u16(&mut payload, message.cause_kind);
    push_u16(&mut payload, message.interaction_phase);
    push_u16(&mut payload, message.interaction_kind);
    push_u16(&mut payload, message.interaction_axis);
    push_u64(&mut payload, message.activation_serial);
    push_u64(&mut payload, message.action);
    push_u32(&mut payload, message.target_index);
    push_u32(&mut payload, message.target_generation);
    push_i32(&mut payload, message.interaction_x);
    push_i32(&mut payload, message.interaction_y);
    push_i32(&mut payload, message.interaction_width);
    push_i32(&mut payload, message.interaction_height);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(IpcMessageKind::WmV1ProjectionRequest, transaction, &payload)
}

pub fn decode_wm_v1_projection_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let cause_kind = cursor.u16()?;
    let interaction_phase = cursor.u16()?;
    let interaction_kind = cursor.u16()?;
    let interaction_axis = cursor.u16()?;
    let activation_serial = cursor.u64()?;
    let action = cursor.u64()?;
    let target_index = cursor.u32()?;
    let target_generation = cursor.u32()?;
    let interaction_x = cursor.i32()?;
    let interaction_y = cursor.i32()?;
    let interaction_width = cursor.i32()?;
    let interaction_height = cursor.i32()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(84);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionRequest {
        connection_epoch,
        request_id,
        scene_generation,
        policy_generation,
        cause_kind,
        interaction_phase,
        interaction_kind,
        interaction_axis,
        activation_serial,
        action,
        target_index,
        target_generation,
        interaction_x,
        interaction_y,
        interaction_width,
        interaction_height,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionBegin {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub active_output: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub placement_count: u32,
    pub indicator_count: u16,
    pub status_count: u16,
}

pub fn encode_wm_v1_projection_begin_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u64(&mut payload, message.active_output);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.placement_count);
    push_u16(&mut payload, message.indicator_count);
    push_u16(&mut payload, message.status_count);
    encode_frame(IpcMessageKind::WmV1ProjectionBegin, transaction, &payload)
}

pub fn decode_wm_v1_projection_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let active_output = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let placement_count = cursor.u32()?;
    let indicator_count = cursor.u16()?;
    let status_count = cursor.u16()?;
    cursor.finish()?;
    let message = WmV1ProjectionBegin {
        connection_epoch,
        request_id,
        base_generation,
        active_output,
        chunk_count,
        output_count,
        placement_count,
        indicator_count,
        status_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_projection_chunk_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1ProjectionChunk, transaction, &payload)
}

pub fn decode_wm_v1_projection_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionEnd {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_projection_end_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionEnd, transaction, &payload)
}

pub fn decode_wm_v1_projection_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionEnd {
        connection_epoch,
        request_id,
        base_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutcome {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_projection_outcome_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionOutcome, transaction, &payload)
}

pub fn decode_wm_v1_projection_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionOutcome {
        connection_epoch,
        request_id,
        scene_generation,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyConfiguration {
    pub connection_epoch: u64,
    pub configuration_generation: u64,
    pub action_count: u16,
    pub style_bits: u16,
    pub focus_ring_width: u32,
    pub focus_ring_color: u32,
    pub frame_width: u32,
    pub frame_focused_color: u32,
    pub frame_unfocused_color: u32,
    pub actions: Vec<u8>,
}

pub fn encode_wm_v1_policy_configuration_frame(
    transaction: TransactionId,
    message: &WmV1PolicyConfiguration,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.actions.len() > 35840 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "actions",
            len: message.actions.len(),
            max: 35840,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.configuration_generation);
    push_u16(&mut payload, message.action_count);
    push_u16(&mut payload, message.style_bits);
    push_u32(&mut payload, message.focus_ring_width);
    push_u32(&mut payload, message.focus_ring_color);
    push_u32(&mut payload, message.frame_width);
    push_u32(&mut payload, message.frame_focused_color);
    push_u32(&mut payload, message.frame_unfocused_color);
    payload.extend_from_slice(&message.actions);
    encode_frame(
        IpcMessageKind::WmV1PolicyConfiguration,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_policy_configuration_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyConfiguration), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyConfiguration {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let configuration_generation = cursor.u64()?;
    let action_count = cursor.u16()?;
    let style_bits = cursor.u16()?;
    let focus_ring_width = cursor.u32()?;
    let focus_ring_color = cursor.u32()?;
    let frame_width = cursor.u32()?;
    let frame_focused_color = cursor.u32()?;
    let frame_unfocused_color = cursor.u32()?;
    let len = payload.len().saturating_sub(40);
    if len > 35840 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "actions",
            len,
            max: 35840,
        });
    }
    let actions = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1PolicyConfiguration {
        connection_epoch,
        configuration_generation,
        action_count,
        style_bits,
        focus_ring_width,
        focus_ring_color,
        frame_width,
        frame_focused_color,
        frame_unfocused_color,
        actions,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyConfigurationOutcome {
    pub connection_epoch: u64,
    pub configuration_generation: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_policy_configuration_outcome_frame(
    transaction: TransactionId,
    message: &WmV1PolicyConfigurationOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.configuration_generation);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(
        IpcMessageKind::WmV1PolicyConfigurationOutcome,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_policy_configuration_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyConfigurationOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyConfigurationOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let configuration_generation = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1PolicyConfigurationOutcome {
        connection_epoch,
        configuration_generation,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyDirty {
    pub connection_epoch: u64,
    pub policy_generation: u64,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_policy_dirty_frame(
    transaction: TransactionId,
    message: &WmV1PolicyDirty,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.policy_generation);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(IpcMessageKind::WmV1PolicyDirty, transaction, &payload)
}

pub fn decode_wm_v1_policy_dirty_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyDirty), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyDirty {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(20);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1PolicyDirty {
        connection_epoch,
        policy_generation,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SessionOperationRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub operation: u64,
    pub target_index: u32,
    pub target_generation: u32,
}

pub fn encode_wm_v1_session_operation_request_frame(
    transaction: TransactionId,
    message: &WmV1SessionOperationRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.operation);
    push_u32(&mut payload, message.target_index);
    push_u32(&mut payload, message.target_generation);
    encode_frame(
        IpcMessageKind::WmV1SessionOperationRequest,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_session_operation_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SessionOperationRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SessionOperationRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let operation = cursor.u64()?;
    let target_index = cursor.u32()?;
    let target_generation = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1SessionOperationRequest {
        connection_epoch,
        request_id,
        operation,
        target_index,
        target_generation,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SessionOperationOutcome {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_session_operation_outcome_frame(
    transaction: TransactionId,
    message: &WmV1SessionOperationOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(
        IpcMessageKind::WmV1SessionOperationOutcome,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_session_operation_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SessionOperationOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SessionOperationOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SessionOperationOutcome {
        connection_epoch,
        request_id,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfilePrepare {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_prepare_frame(
    transaction: TransactionId,
    message: &WmV1ProfilePrepare,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfilePrepare, transaction, &payload)
}

pub fn decode_wm_v1_profile_prepare_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfilePrepare), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfilePrepare {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfilePrepare {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfilePrepared {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_prepared_frame(
    transaction: TransactionId,
    message: &WmV1ProfilePrepared,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfilePrepared, transaction, &payload)
}

pub fn decode_wm_v1_profile_prepared_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfilePrepared), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfilePrepared {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfilePrepared {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileActivate {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_activate_frame(
    transaction: TransactionId,
    message: &WmV1ProfileActivate,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfileActivate, transaction, &payload)
}

pub fn decode_wm_v1_profile_activate_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileActivate), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileActivate {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfileActivate {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileActive {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_active_frame(
    transaction: TransactionId,
    message: &WmV1ProfileActive,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfileActive, transaction, &payload)
}

pub fn decode_wm_v1_profile_active_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileActive), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileActive {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfileActive {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileRollback {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_rollback_frame(
    transaction: TransactionId,
    message: &WmV1ProfileRollback,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfileRollback, transaction, &payload)
}

pub fn decode_wm_v1_profile_rollback_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileRollback), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileRollback {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfileRollback {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileRolledBack {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_rolled_back_frame(
    transaction: TransactionId,
    message: &WmV1ProfileRolledBack,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfileRolledBack, transaction, &payload)
}

pub fn decode_wm_v1_profile_rolled_back_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileRolledBack), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileRolledBack {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfileRolledBack {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}
