[workspace]
members = [
    "crates/sophia-conformance",
    "crates/sophia-cli",
    "crates/sophia-backend-live",
    "crates/sophia-broker",
    "crates/sophia-config",
    "crates/sophia-drm-out-fence",
    "crates/sophia-engine",
    "crates/sophia-linux-peer",
    "crates/sophia-portal",
    "crates/sophia-protocol",
    "crates/sophia-renderer-native-egl",
    "crates/sophia-renderer-live",
    "crates/sophia-runtime",
    "crates/sophia-shell-client",
    "crates/sophia-session",
    "crates/sophia-sysv-shm",
    "crates/sophia-wm-demo",
    "crates/sophia-x-authority",
    "crates/sophia-xshmfence",
    "tools/sophia-policy-protocol-gen",
    "crates/xtask",
]
default-members = [
    "crates/sophia-cli",
    "crates/sophia-backend-live",
    "crates/sophia-broker",
    "crates/sophia-config",
    "crates/sophia-drm-out-fence",
    "crates/sophia-engine",
    "crates/sophia-portal",
    "crates/sophia-protocol",
    "crates/sophia-renderer-native-egl",
    "crates/sophia-renderer-live",
    "crates/sophia-runtime",
    "crates/sophia-shell-client",
    "crates/sophia-session",
    "crates/sophia-sysv-shm",
    "crates/sophia-wm-demo",
    "crates/sophia-x-authority",
    "crates/sophia-xshmfence",
]
resolver = "3"

[workspace.package]
authors = ["Mason Austin Green"]
edition = "2024"
license = "BSD-3-Clause"
version = "0.1.0"
rust-version = "1.96"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
new_without_default = "allow"

[workspace.dependencies]
kdl = { version = "6.7.1", default-features = false, features = ["span"] }
rustix = { version = "1.1", default-features = false, features = ["fs", "process"] }
sha2 = "0.10.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
xcursor = "0.3.10"
