[package]
name = "sophia-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rustix = { version = "1.1", default-features = false, features = ["net", "process", "std", "event", "rand"] }
sophia-linux-peer = { path = "../sophia-linux-peer" }
sophia-protocol = { path = "../sophia-protocol" }
tracing-subscriber.workspace = true

[dev-dependencies]
sophia-engine = { path = "../sophia-engine" }
sophia-shell-client = { path = "../sophia-shell-client" }
sophia-wm-demo = { path = "../sophia-wm-demo" }

[lints]
workspace = true
