/* @generated by sophia-policy-protocol-gen; do not edit. */
#ifndef SOPHIA_WM_V1_H
#define SOPHIA_WM_V1_H

#include <stddef.h>
#include <stdint.h>

#define SOPHIA_WM_INTERFACE_MAJOR 1u
#define SOPHIA_WM_INTERFACE_REVISION 3u
#define SOPHIA_WM_MAX_OUTPUTS 16u
#define SOPHIA_WM_MAX_SURFACES 1024u
#define SOPHIA_WM_MAX_BINDINGS 256u

#define SOPHIA_WM_CAPABILITY_BINDINGS (UINT64_C(1) << 0)
#define SOPHIA_WM_CAPABILITY_ACTIONS (UINT64_C(1) << 1)
#define SOPHIA_WM_CAPABILITY_MULTI_OUTPUT (UINT64_C(1) << 2)
#define SOPHIA_WM_CAPABILITY_POINTER_INTERACTIONS (UINT64_C(1) << 3)
#define SOPHIA_WM_CAPABILITY_CHROME (UINT64_C(1) << 4)
#define SOPHIA_WM_CAPABILITY_POLICY_DIRTY (UINT64_C(1) << 5)
#define SOPHIA_WM_CAPABILITY_CONFIGURATION (UINT64_C(1) << 6)
#define SOPHIA_WM_CAPABILITY_SESSION_OPERATIONS (UINT64_C(1) << 7)
#define SOPHIA_WM_CAPABILITY_INDICATORS (UINT64_C(1) << 8)
#define SOPHIA_WM_CAPABILITY_PROFILE_ACTIVATION (UINT64_C(1) << 9)
#define SOPHIA_WM_CAPABILITY_LAUNCH_PLACEMENT (UINT64_C(1) << 10)
#define SOPHIA_WM_CAPABILITY_TAB_GROUPS (UINT64_C(1) << 11)
#define SOPHIA_WM_CAPABILITY_TRANSLATION_GROUPS (UINT64_C(1) << 12)
#define SOPHIA_WM_CAPABILITY_POINTER_FOCUS (UINT64_C(1) << 13)
#define SOPHIA_WM_CAPABILITY_LAUNCH_ORIGIN (UINT64_C(1) << 14)

#define SOPHIA_WM_OUTCOME_COMMITTED 1u
#define SOPHIA_WM_OUTCOME_REJECTED_STALE 2u
#define SOPHIA_WM_OUTCOME_REJECTED_INVALID 3u
#define SOPHIA_WM_OUTCOME_TIMED_OUT 4u
#define SOPHIA_WM_OUTCOME_DISCONNECTED 5u
#define SOPHIA_WM_OUTCOME_PROFILE_ACCEPTED 1u
#define SOPHIA_WM_OUTCOME_PROFILE_REJECTED_IDENTITY 2u
#define SOPHIA_WM_OUTCOME_PROFILE_REJECTED_STATE 3u

enum sophia_wm_v1_status {
    SOPHIA_WM_V1_OK = 0,
    SOPHIA_WM_V1_TRUNCATED = 1,
    SOPHIA_WM_V1_BAD_MAGIC = 2,
    SOPHIA_WM_V1_UNSUPPORTED_FRAME_VERSION = 3,
    SOPHIA_WM_V1_WRONG_MESSAGE_KIND = 4,
    SOPHIA_WM_V1_PAYLOAD_TOO_LARGE = 5,
    SOPHIA_WM_V1_RESERVED_NONZERO = 6,
    SOPHIA_WM_V1_TRAILING_BYTES = 7,
    SOPHIA_WM_V1_INVALID_TRANSACTION = 8,
    SOPHIA_WM_V1_FIELD_TOO_LARGE = 9
};

#define SOPHIA_WM_V1_SNAPSHOT_OUTPUT_RECORD_KIND 1u
#define SOPHIA_WM_V1_SNAPSHOT_OUTPUT_RECORD_SIZE 56u
#define SOPHIA_WM_V1_SNAPSHOT_OUTPUT_RECORD_MAX 16u
struct sophia_wm_v1_snapshot_output_record {
    uint64_t output;
    uint64_t generation;
    uint32_t focus_index;
    uint32_t focus_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t work_x;
    int32_t work_y;
    int32_t work_width;
    int32_t work_height;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_output_record(const struct sophia_wm_v1_snapshot_output_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_output_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_output_record *record);

#define SOPHIA_WM_V1_SNAPSHOT_SURFACE_RECORD_KIND 2u
#define SOPHIA_WM_V1_SNAPSHOT_SURFACE_RECORD_SIZE 80u
#define SOPHIA_WM_V1_SNAPSHOT_SURFACE_RECORD_MAX 1024u
struct sophia_wm_v1_snapshot_surface_record {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t state_generation;
    uint64_t current_output;
    uint16_t capability_bits;
    uint16_t kind;
    uint16_t request_state_bits;
    uint16_t current_state_bits;
    uint32_t transient_index;
    uint32_t transient_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t min_width;
    int32_t min_height;
    int32_t max_width;
    int32_t max_height;
    int32_t exact_width;
    int32_t exact_height;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_surface_record(const struct sophia_wm_v1_snapshot_surface_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_surface_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_surface_record *record);

#define SOPHIA_WM_V1_SNAPSHOT_ACTION_RECORD_KIND 3u
#define SOPHIA_WM_V1_SNAPSHOT_ACTION_RECORD_SIZE 140u
#define SOPHIA_WM_V1_SNAPSHOT_ACTION_RECORD_MAX 256u
struct sophia_wm_v1_snapshot_action_record {
    uint64_t action;
    uint16_t session_operation_slot;
    uint16_t name_len;
    uint8_t name[128];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_action_record(const struct sophia_wm_v1_snapshot_action_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_action_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_action_record *record);

#define SOPHIA_WM_V1_SNAPSHOT_SESSION_OPERATION_RECORD_KIND 4u
#define SOPHIA_WM_V1_SNAPSHOT_SESSION_OPERATION_RECORD_SIZE 12u
#define SOPHIA_WM_V1_SNAPSHOT_SESSION_OPERATION_RECORD_MAX 256u
struct sophia_wm_v1_snapshot_session_operation_record {
    uint64_t operation;
    uint16_t slot;
    uint16_t target_bits;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_session_operation_record(const struct sophia_wm_v1_snapshot_session_operation_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_session_operation_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_snapshot_session_operation_record *record);

#define SOPHIA_WM_V1_PROJECTION_OUTPUT_RECORD_KIND 1u
#define SOPHIA_WM_V1_PROJECTION_OUTPUT_RECORD_SIZE 24u
#define SOPHIA_WM_V1_PROJECTION_OUTPUT_RECORD_MAX 16u
struct sophia_wm_v1_projection_output_record {
    uint64_t output;
    uint32_t placement_count;
    uint32_t focus_index;
    uint32_t focus_generation;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_output_record(const struct sophia_wm_v1_projection_output_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_output_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_output_record *record);

#define SOPHIA_WM_V1_PROJECTION_PLACEMENT_RECORD_KIND 2u
#define SOPHIA_WM_V1_PROJECTION_PLACEMENT_RECORD_SIZE 60u
#define SOPHIA_WM_V1_PROJECTION_PLACEMENT_RECORD_MAX 1024u
struct sophia_wm_v1_projection_placement_record {
    uint32_t surface_index;
    uint32_t surface_generation;
    uint64_t state_generation;
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
    int32_t requested_width;
    int32_t requested_height;
    int32_t crop_x;
    int32_t crop_y;
    int32_t crop_width;
    int32_t crop_height;
    uint16_t transform;
    uint16_t presentation_bits;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_placement_record(const struct sophia_wm_v1_projection_placement_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_placement_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_placement_record *record);

#define SOPHIA_WM_V1_PROJECTION_INDICATOR_RECORD_KIND 3u
#define SOPHIA_WM_V1_PROJECTION_INDICATOR_RECORD_SIZE 64u
#define SOPHIA_WM_V1_PROJECTION_INDICATOR_RECORD_MAX 256u
struct sophia_wm_v1_projection_indicator_record {
    uint64_t output;
    uint32_t slot;
    uint64_t indicator;
    uint64_t action;
    uint16_t state_bits;
    uint16_t label_len;
    uint8_t label[32];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_indicator_record(const struct sophia_wm_v1_projection_indicator_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_indicator_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_indicator_record *record);

#define SOPHIA_WM_V1_PROJECTION_OUTPUT_STATUS_RECORD_KIND 4u
#define SOPHIA_WM_V1_PROJECTION_OUTPUT_STATUS_RECORD_SIZE 48u
#define SOPHIA_WM_V1_PROJECTION_OUTPUT_STATUS_RECORD_MAX 16u
struct sophia_wm_v1_projection_output_status_record {
    uint64_t output;
    uint16_t focus_bits;
    uint16_t layout_len;
    uint8_t layout[32];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_output_status_record(const struct sophia_wm_v1_projection_output_status_record *record, uint8_t *out, size_t capacity);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_output_status_record(const uint8_t *data, size_t data_len, size_t index, struct sophia_wm_v1_projection_output_status_record *record);

struct sophia_wm_v1_client_hello {
    uint16_t minimum_revision;
    uint16_t maximum_revision;
    uint64_t capabilities;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_client_hello(const struct sophia_wm_v1_client_hello *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_client_hello(const uint8_t *frame, size_t frame_len, struct sophia_wm_v1_client_hello *message);

struct sophia_wm_v1_server_welcome {
    uint16_t selected_revision;
    uint64_t capabilities;
    uint64_t connection_epoch;
    uint16_t max_outputs;
    uint16_t max_bindings;
    uint32_t max_surfaces;
    uint32_t max_chunk_bytes;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_server_welcome(const struct sophia_wm_v1_server_welcome *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_server_welcome(const uint8_t *frame, size_t frame_len, struct sophia_wm_v1_server_welcome *message);

struct sophia_wm_v1_snapshot_begin {
    uint64_t connection_epoch;
    uint64_t scene_generation;
    uint64_t active_output;
    uint16_t chunk_count;
    uint16_t output_count;
    uint32_t surface_count;
    uint16_t action_count;
    uint16_t session_operation_count;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_begin(uint64_t transaction, const struct sophia_wm_v1_snapshot_begin *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_begin(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_begin *message);

struct sophia_wm_v1_snapshot_chunk {
    uint64_t connection_epoch;
    uint16_t ordinal;
    uint16_t record_kind;
    uint32_t item_count;
    const uint8_t *data;
    size_t data_len;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_chunk(uint64_t transaction, const struct sophia_wm_v1_snapshot_chunk *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_chunk(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_chunk *message);

struct sophia_wm_v1_snapshot_end {
    uint64_t connection_epoch;
    uint64_t scene_generation;
    uint16_t chunk_count;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_snapshot_end(uint64_t transaction, const struct sophia_wm_v1_snapshot_end *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_snapshot_end(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_snapshot_end *message);

struct sophia_wm_v1_projection_request {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint64_t scene_generation;
    uint64_t policy_generation;
    uint16_t cause_kind;
    uint16_t interaction_phase;
    uint16_t interaction_kind;
    uint16_t interaction_axis;
    uint64_t activation_serial;
    uint64_t action;
    uint32_t target_index;
    uint32_t target_generation;
    int32_t interaction_x;
    int32_t interaction_y;
    int32_t interaction_width;
    int32_t interaction_height;
    uint16_t affected_output_count;
    const uint8_t *affected_outputs;
    size_t affected_outputs_len;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_request(uint64_t transaction, const struct sophia_wm_v1_projection_request *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_request *message);

struct sophia_wm_v1_projection_begin {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint64_t base_generation;
    uint64_t active_output;
    uint16_t chunk_count;
    uint16_t output_count;
    uint32_t placement_count;
    uint16_t indicator_count;
    uint16_t status_count;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_begin(uint64_t transaction, const struct sophia_wm_v1_projection_begin *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_begin(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_begin *message);

struct sophia_wm_v1_projection_chunk {
    uint64_t connection_epoch;
    uint16_t ordinal;
    uint16_t record_kind;
    uint32_t item_count;
    const uint8_t *data;
    size_t data_len;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_chunk(uint64_t transaction, const struct sophia_wm_v1_projection_chunk *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_chunk(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_chunk *message);

struct sophia_wm_v1_projection_end {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint64_t base_generation;
    uint16_t chunk_count;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_end(uint64_t transaction, const struct sophia_wm_v1_projection_end *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_end(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_end *message);

struct sophia_wm_v1_projection_outcome {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint64_t scene_generation;
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_projection_outcome(uint64_t transaction, const struct sophia_wm_v1_projection_outcome *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_projection_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_projection_outcome *message);

struct sophia_wm_v1_policy_configuration {
    uint64_t connection_epoch;
    uint64_t configuration_generation;
    uint16_t action_count;
    uint16_t style_bits;
    uint32_t focus_ring_width;
    uint32_t focus_ring_color;
    uint32_t frame_width;
    uint32_t frame_focused_color;
    uint32_t frame_unfocused_color;
    const uint8_t *actions;
    size_t actions_len;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_policy_configuration(uint64_t transaction, const struct sophia_wm_v1_policy_configuration *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_policy_configuration(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_configuration *message);

struct sophia_wm_v1_policy_configuration_outcome {
    uint64_t connection_epoch;
    uint64_t configuration_generation;
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_policy_configuration_outcome(uint64_t transaction, const struct sophia_wm_v1_policy_configuration_outcome *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_policy_configuration_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_configuration_outcome *message);

struct sophia_wm_v1_policy_dirty {
    uint64_t connection_epoch;
    uint64_t policy_generation;
    uint16_t affected_output_count;
    const uint8_t *affected_outputs;
    size_t affected_outputs_len;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_policy_dirty(uint64_t transaction, const struct sophia_wm_v1_policy_dirty *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_policy_dirty(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_policy_dirty *message);

struct sophia_wm_v1_session_operation_request {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint64_t operation;
    uint32_t target_index;
    uint32_t target_generation;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_session_operation_request(uint64_t transaction, const struct sophia_wm_v1_session_operation_request *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_session_operation_request(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_session_operation_request *message);

struct sophia_wm_v1_session_operation_outcome {
    uint64_t connection_epoch;
    uint64_t request_id;
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_session_operation_outcome(uint64_t transaction, const struct sophia_wm_v1_session_operation_outcome *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_session_operation_outcome(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_session_operation_outcome *message);

struct sophia_wm_v1_profile_prepare {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_prepare(uint64_t transaction, const struct sophia_wm_v1_profile_prepare *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_prepare(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_prepare *message);

struct sophia_wm_v1_profile_prepared {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_prepared(uint64_t transaction, const struct sophia_wm_v1_profile_prepared *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_prepared(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_prepared *message);

struct sophia_wm_v1_profile_activate {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_activate(uint64_t transaction, const struct sophia_wm_v1_profile_activate *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_activate(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_activate *message);

struct sophia_wm_v1_profile_active {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_active(uint64_t transaction, const struct sophia_wm_v1_profile_active *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_active(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_active *message);

struct sophia_wm_v1_profile_rollback {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_rollback(uint64_t transaction, const struct sophia_wm_v1_profile_rollback *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_rollback(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_rollback *message);

struct sophia_wm_v1_profile_rolled_back {
    uint64_t connection_epoch;
    uint64_t profile_generation;
    uint8_t profile_digest[32];
    uint16_t outcome;
};
enum sophia_wm_v1_status sophia_wm_v1_encode_profile_rolled_back(uint64_t transaction, const struct sophia_wm_v1_profile_rolled_back *message, uint8_t *out, size_t capacity, size_t *written);
enum sophia_wm_v1_status sophia_wm_v1_decode_profile_rolled_back(const uint8_t *frame, size_t frame_len, uint64_t *transaction, struct sophia_wm_v1_profile_rolled_back *message);

#endif
