[package]
name = "sophia-x-authority"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rustix = { version = "1.1", default-features = false, features = ["fs", "net", "std", "time"] }
sophia-portal = { path = "../sophia-portal" }
sophia-protocol = { path = "../sophia-protocol" }
sophia-sysv-shm = { path = "../sophia-sysv-shm" }
xkbcommon = "0.8"
tracing.workspace = true

[lints]
workspace = true
