[package]
name = "sophia-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "sophia"
path = "src/main.rs"

[dependencies]
sophia-backend-live = { path = "../sophia-backend-live", optional = true, default-features = false }
sophia-broker = { path = "../sophia-broker" }
sophia-config = { path = "../sophia-config" }
sophia-engine = { path = "../sophia-engine" }
sophia-portal = { path = "../sophia-portal" }
sophia-protocol = { path = "../sophia-protocol" }
sophia-runtime = { path = "../sophia-runtime" }
sophia-session = { path = "../sophia-session", default-features = false }
sophia-wm-demo = { path = "../sophia-wm-demo" }
sophia-x-authority = { path = "../sophia-x-authority" }
sophia-xshmfence = { path = "../sophia-xshmfence" }
tracing.workspace = true
tracing-subscriber.workspace = true
rustix = { version = "1.1", default-features = false, features = ["process", "rand", "system", "fs"] }
x11rb = { version = "0.13.1", features = ["shm", "render", "dri3"] }
sophia-sysv-shm = { path = "../sophia-sysv-shm" }

[features]
default = []
native-session = ["sophia-session/native-session", "sophia-backend-live/gbm-probe", "sophia-backend-live/libdrm-events", "sophia-backend-live/drm-hotplug", "sophia-backend-live/libinput-events", "sophia-backend-live/seat-control"]
atomic-scanout-live = ["native-session"]
atomic-scanout-smoke-live = ["atomic-scanout-live"]

[lints]
workspace = true
